name: Build & Deploy Docker App

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: nhkwardana30/githuactioncicd-service-backend-1
  CONTAINER_NAME: service-backend-1
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:latest .

    - name: Push image to DockerHub
      run: docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest

  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull $REGISTRY/${{ env.IMAGE_NAME }}:latest
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -d --name $CONTAINER_NAME -p 4000:4000 $REGISTRY/${{ env.IMAGE_NAME }}:latest
